### ISSUE TITLE
DnD poll issues/conflicts??

### ISSUE THREAD

**Issue by CasualGryphon** [LuxGracetail/PS-Roleplaying-Bot#3] opened 2015-12-21 17:58 UTC
http://hastebin.com/raw/mijajiriwa

http://hastebin.com/raw/bigibifaqe

Maybe fix DnD's void mess up, and make the bot less spammy when this occurs?
or just tell every moderator to write it a certain way :I

**Comment by LuxGracetail** [comment] 2015-12-22 14:41
Closing because duplicate of issue 2.

**Closed as completed by LuxGracetail** 2015-12-22 14:41 UTC
Labels: bug, duplicate
